import { Task } from "@/types/kanban";

export const SAMPLE_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Yeni yerler bulun, fotoğraf çekimi düzenleyin, tanıtımlarımız için en az 100 fotoğraf hazırlayın",
    description: "Portföy tanıtımları için yüksek kaliteli fotoğraflar gerekli",
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    statusColumn: "overdue",
    priority: "high",
    labels: ["fotoğraf", "tanıtım"],
    commentsCount: 2,
    assignedUsers: [
      { id: "user-1", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John", name: "John" },
      { id: "user-2", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane", name: "Jane" },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "task-2",
    title: "Kadiköy'deki daire için anlaşmayı sonuçlandırın",
    description: "Müşteri ile görüşme planlandı, sözleşme hazırlığı yapılacak",
    dueDate: new Date().toISOString(),
    statusColumn: "today",
    priority: "urgent",
    labels: ["acil", "sözleşme"],
    commentsCount: 7,
    assignedUsers: [
      { id: "user-1", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John", name: "John" },
      { id: "user-2", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane", name: "Jane" },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "task-3",
    title: "Renk paletleri",
    description: "Yeni projeler için renk paleti seçimi",
    dueDate: new Date().toISOString(),
    statusColumn: "today",
    priority: "medium",
    labels: ["yeni", "tasarım"],
    commentsCount: 5,
    assignedUsers: [
      { id: "user-1", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John", name: "John" },
    ],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=400",
  },
  {
    id: "task-4",
    title: "Apartman tadilatı: sıhhi tesisat ve demirbaşlar",
    description: "Tadilat işlemleri için planlama ve bütçe hazırlığı",
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    statusColumn: "tomorrow",
    priority: "high",
    labels: ["tadilat"],
    commentsCount: 1,
    assignedUsers: [
      { id: "user-2", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane", name: "Jane" },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "task-5",
    title: "Mobilyaları hazırlayın: masalar, sandalyeler, yataklar, aynalar vb.",
    description: "Stok kontrolü ve sipariş hazırlığı",
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    statusColumn: "tomorrow",
    priority: "medium",
    labels: ["mobilya", "yarın"],
    commentsCount: 2,
    assignedUsers: [
      { id: "user-1", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John", name: "John" },
    ],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "task-6",
    title: "Yeni iç dizayn + yeniden tasarlanmış düzen",
    description: "Modern ve fonksiyonel iç mekan tasarımı",
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    statusColumn: "tomorrow",
    priority: "high",
    labels: ["tasarım"],
    commentsCount: 5,
    assignedUsers: [
      { id: "user-1", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John", name: "John" },
      { id: "user-2", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane", name: "Jane" },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
  },
  {
    id: "task-7",
    title: "Şehir inşa komitesi, yeni planı onaylatın",
    description: "Resmi onay süreçleri ve belge hazırlığı",
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    statusColumn: "nextWeek",
    priority: "urgent",
    labels: ["onay", "belge"],
    commentsCount: 7,
    assignedUsers: [
      { id: "user-1", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John", name: "John" },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400",
  },
  {
    id: "task-8",
    title: "Mutfak - yeniden tasarlanmış iç mekan, yeni ekipman sipariş edin, planı kesinleştirin",
    description: "Mutfak renovasyonu için detaylı planlama",
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    statusColumn: "nextWeek",
    priority: "high",
    labels: ["yeni", "mutfak"],
    commentsCount: 7,
    assignedUsers: [
      { id: "user-2", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane", name: "Jane" },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "task-9",
    title: "Oturma odası: aydınlatma armatürleri",
    description: "Aydınlatma tasarımı ve ürün seçimi",
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    statusColumn: "nextMonth",
    priority: "low",
    labels: ["aydınlatma"],
    commentsCount: 0,
    assignedUsers: [
      { id: "user-1", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John", name: "John" },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "task-10",
    title: "İkinci kat planı ve düzen",
    description: "Mimari plan çizimi ve onay süreci",
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    statusColumn: "nextMonth",
    priority: "medium",
    labels: ["plan"],
    commentsCount: 5,
    assignedUsers: [
      { id: "user-2", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane", name: "Jane" },
    ],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400",
  },
  {
    id: "task-11",
    title: "Eylül'deki projeler için belgeleri hazırlayın",
    description: "Eylül ayı proje dosyalarının hazırlanması",
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    statusColumn: "nextMonth",
    priority: "medium",
    labels: ["belge"],
    commentsCount: 0,
    assignedUsers: [
      { id: "user-1", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John", name: "John" },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

